services:
  - type: web
    name: shared-board-client
    env: node  # Use Node.js environment
    repo: https://github.com/erkintunca/shared-board
    buildCommand: npm run build  # Add build command
    startCommand: npm run start  # Add start command
    publishPath: dist  # Update publish path
    envVars:
      - key: VITE_API_URL
        value: https://shared-board-y6cp.onrender.com